CREATE TABLE dataObject (
id INT NOT NULL UNIQUE,
title CHAR(20) NOT NULL,
number BIGINT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
login CHAR(10) NOT NULL,
password CHAR(10)
role CHAR(10) NOT NULL,
PRIMARY KEY (id)
);