CREATE TABLE dataObject (
id INT NOT NULL UNIQUE,
title CHAR(10) NOT NULL,
number BIGINT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
user CHAR(10) NOT NULL,
role CHAR(10) NOT NULL,
PRIMARY KEY (id)
);